name: Update Upcoming Shoppers, Product Embeddings & Recommended Products Data

env:
  SERVICE_NAME: ecommerce-api-production
  PROJECT_ID: ecommerce-data-project-444616

on:
  schedule:
    - cron: '0 0 1 */3 *' # Runs at 12:01 AM of 1st day of every 3rd month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/data-update-requirements.txt

      - name: Update Product Embeddings
        run: python backend/product-embeddings.py

      - name: Update Upcoming Shoppers
        run: python backend/upcoming-shoppers.py

      - name: Update Upcoming Shopper Product Recommendations
        env:
          GCP_SERVICE_ACCOUNT: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
        run: python backend/recs-spreadsheet.py
