name: Deploy Frontend to Cloud Run Production Environment

env:
  SERVICE_NAME: web-app-frontend-production
  PROJECT_ID: ecommerce-data-project-444616
  DOCKER_IMAGE_URL: europe-west10-docker.pkg.dev/ecommerce-data-project-444616/product-recs-api/production-frontend
  STAGING_OR_PROD: PROD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/production-frontend-cicd.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/production-frontend-cicd.yaml'

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker with GCP
        run: |
          gcloud auth configure-docker europe-west10-docker.pkg.dev

      - name: Build and Push Docker Image to GCP Artifact Registry
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f frontend/Dockerfile frontend/.
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run Staging Environment
        run: |  # Set CPU & memory to approx. same as local computer
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --set-env-vars VITE_STAGING_OR_PROD=${{ env.STAGING_OR_PROD }} \
            --platform managed \
            --region europe-west10 \
            --allow-unauthenticated \
            --port=5173 \
            --memory=16Gi \
            --cpu=8 \
            --timeout=3600 \
            --max-instances=1 \
            --min-instances=0

