name: Deploy Backend to Cloud Run Staging Area

env:
  SERVICE_NAME: product-recs-api
  PROJECT_ID: ecommerce-data-project-444616
  DOCKER_IMAGE_URL: europe-west10-docker.pkg.dev/ecommerce-data-project-444616/product-recs-api/api
  STAGING_OR_PROD: STAGING

on:
  push:
    branches:
      - staging
    paths:
      - 'backend/**'
      - '.github/workflows/staging-backend-cicd.yaml'
  pull_request:
    branches:
      - staging
    paths:
      - 'backend/**'
      - '.github/workflows/staging-backend-cicd.yaml'

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker with GCP
        run: |
          gcloud auth configure-docker europe-west10-docker.pkg.dev

      - name: Build and Push Docker Image to GCP Artifact Registry
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f backend/Dockerfile backend/.
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run Staging Environment
        run: |  # Set CPU & memory to approx. same as local computer
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --set-env-vars STAGING_OR_PROD=${{ env.STAGING_OR_PROD }} \
            --platform managed \
            --region europe-west10 \
            --allow-unauthenticated \
            --port=8000 \
            --memory=16Gi \
            --cpu=8 \
            --timeout=300 \
            --max-instances=1

