name: Deploy Backend to Cloud Run Staging Area

env:
  SERVICE_NAME: web-app-frontend
  PROJECT_ID: ecommerce-data-project-444616
  DOCKER_IMAGE_URL: europe-west10-docker.pkg.dev/ecommerce-data-project-444616/product-recs-api/staging-frontend

on:
  push:
    branches:
      - staging
    paths:
      - 'frontend/**'
      - '.github/workflows/staging-frontend-cicd.yaml'
  pull_request:
    branches:
      - staging
    paths:
      - 'frontend/**'
      - '.github/workflows/staging-frontend-cicd.yaml'

jobs:
  dockerize-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker with GCP
        run: |
          gcloud auth configure-docker europe-west10-docker.pkg.dev

      - name: Build and Push Docker Image to GCP Artifact Registry
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f frontend/Dockerfile frontend/.
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run Staging Environment
        run: |  # Set CPU & memory to approx. same as local computer
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.DOCKER_IMAGE_URL }}:latest \
            --platform managed \
            --region europe-west10 \
            --allow-unauthenticated \
            --port=8001 \
            --memory=16Gi \
            --cpu=8 \
            --timeout=3600 \
            --max-instances=1

